// Seasonal depth and tactics guide for Latvian lakes. Depths in meters.
// Names: Latvian · English · Russian. Seasonal bands are typical preferences;
// advice.js adapts them to each lake's actual depth and structure.

export const SPECIES = [
  {
    id: 'pike',
    lv: 'Līdaka',
    en: 'Pike',
    ru: 'Щука',
    badge: 'LĪ',
    color: '#5b8c3e',
    lures: 'Spoons, jerkbaits, big soft swimbaits; dead roach under a float',
    spawnTemp: '4–11 °C, right after ice-out',
    seasons: {
      spring: { depth: [0.5, 2.5], where: 'Flooded shallows and reed edges', tip: 'First to spawn — they pile into the warmest shallow bays as the ice goes. Slow, shallow presentations.' },
      summer: { depth: [2, 5], where: 'Weedline edges and bay mouths', tip: 'Burn spoons over the weed tops early; big fish drop to the cooler outer edge by day. Note the 1 May–15 June closed season.' },
      fall: { depth: [2, 6], where: 'Deep weed edges and points', tip: 'Cooling water and turnover put big pike on the feed — this is trophy time with big swimbaits.' },
      winter: { depth: [2, 6], where: 'Weed flats near drop-offs, under the ice', tip: 'Set dead-bait rigs just off the last green weeds; midday is often best.' },
    },
  },
  {
    id: 'perch',
    lv: 'Asaris',
    en: 'Perch',
    ru: 'Окунь',
    badge: 'AS',
    color: '#b0782f',
    lures: 'Small spinners, drop-shot, 5–7 cm soft plastics, vertical jigs',
    spawnTemp: '7–12 °C, ribbons over weed & wood',
    seasons: {
      spring: { depth: [1, 3], where: 'Warming shallows and reed edges', tip: 'Schools roam the warming banks draping spawn over weed and brush — keep moving until you contact fish.' },
      summer: { depth: [2, 6], where: 'Weedlines, islands, humps; open-water bait schools', tip: 'They hold just below the thermocline and herd baitfish — watch for surface busts on calm evenings.' },
      fall: { depth: [3, 8], where: 'Deeper edges and basins as water cools', tip: 'Big ones school tight near bottom after turnover — drop-shot slowly through them.' },
      winter: { depth: [4, 10], where: 'Basins and deep flats (ice season)', tip: 'Classic Latvian ice target — small balancers and mormyshkas; drill lots of holes to find the school.' },
    },
  },
  {
    id: 'zander',
    lv: 'Zandarts',
    en: 'Zander',
    ru: 'Судак',
    badge: 'ZA',
    color: '#c9a227',
    lures: 'Soft plastics on jigheads, deep cranks; casting shallows after dark',
    spawnTemp: '8–15 °C, hard sand/gravel bottom',
    seasons: {
      spring: { depth: [2, 5], where: 'Hard-bottom edges near sand/gravel', tip: 'Spawn on clean hard bottom at 0.5–3 m; protected during the spring spawn on many waters — check the rules first.' },
      summer: { depth: [3, 8], where: 'Deep edges by day, shallow flats at night', tip: 'Daytime: drag jigs along the deepest breaks near the thermocline. Night: cast shallow cranks over the flats.' },
      fall: { depth: [4, 10], where: 'Deep basins and channel edges', tip: 'Slow, bottom-hugging jigs. The evening bite window is short but reliable.' },
      winter: { depth: [5, 12], where: 'Deepest basins (ice season)', tip: 'Vertical jigging with ripper baits near bottom; dusk is prime.' },
    },
  },
  {
    id: 'bream',
    lv: 'Plaudis',
    en: 'Bream',
    ru: 'Лещ',
    badge: 'PL',
    color: '#3b8ea5',
    lures: 'Feeder rigs with worms/maggots, groundbait; float rod near reeds',
    spawnTemp: '12–16 °C, noisy nights in the reeds',
    seasons: {
      spring: { depth: [2, 4], where: 'Warm bays before spawning in the reeds', tip: 'Pre-bait a spot for an evening session as the shallows warm.' },
      summer: { depth: [3, 7], where: 'Soft-bottom flats and basin edges', tip: 'Classic feeder water — fish dawn and dusk over a baited patch off the weedline.' },
      fall: { depth: [4, 8], where: 'Deeper soft-bottom areas', tip: 'Schools group up deep after turnover; longer sessions and heavier baiting pay off.' },
      winter: { depth: [5, 10], where: 'Deep basins (ice season)', tip: 'Mormyshka with bloodworms over pre-baited holes; patience wins.' },
    },
  },
  {
    id: 'roach',
    lv: 'Rauda',
    en: 'Roach',
    ru: 'Плотва',
    badge: 'RA',
    color: '#7a6fd0',
    lures: 'Light float rig with bread, maggots or hemp; tiny jigs under ice',
    spawnTemp: '10–15 °C, dense weed',
    seasons: {
      spring: { depth: [1, 3], where: 'Shallow warm bays, reed fringes', tip: 'Huge pre-spawn schools in the first warm bays — light float tackle is all you need.' },
      summer: { depth: [1.5, 4], where: 'Weed edges and gaps in the vegetation', tip: 'Loose-feed little and often; fish the margins at first light.' },
      fall: { depth: [2, 6], where: 'Deeper weed edges', tip: 'Slower and deeper as water cools — a waggler at range works well.' },
      winter: { depth: [3, 7], where: 'Basin edges (ice season)', tip: 'Steady ice-fishing target all winter; feed a hole and keep it going.' },
    },
  },
  {
    id: 'tench',
    lv: 'Līnis',
    en: 'Tench',
    ru: 'Линь',
    badge: 'LN',
    color: '#3f9e6c',
    lures: 'Corn, worms or bread on the bottom tight to reeds and lilies',
    spawnTemp: '18–20 °C, late spawner',
    seasons: {
      spring: { depth: [1, 2.5], where: 'Muddy, weedy bays as they warm', tip: 'Watch for pin-head bubbles over mud — feeding tench give themselves away.' },
      summer: { depth: [1, 3], where: 'Lily pads, reed pockets, weedy margins', tip: 'Dawn is everything. Fish a clear pocket in the weeds, bait it the evening before.' },
      fall: { depth: [1.5, 4], where: 'Last green weed beds', tip: 'Bite slows with cooling water — pick the warmest afternoons.' },
      winter: { depth: [2, 5], where: 'Deeper soft bottom (mostly dormant)', tip: 'Rarely caught through the ice — better to target other species.' },
    },
  },
  {
    id: 'carp',
    lv: 'Karpa',
    en: 'Carp',
    ru: 'Карп / Сазан',
    badge: 'KA',
    color: '#8c5d43',
    lures: 'Boilies, corn, tiger nuts on hair rigs over baited spots',
    spawnTemp: '18–22 °C, weedy shallows',
    seasons: {
      spring: { depth: [1.5, 4], where: 'Warming shallow flats', tip: 'They follow the sun — find the warmest water in the lake and bait it.' },
      summer: { depth: [1, 4], where: 'Margins at night, flats and plateaus', tip: 'Night sessions near the margins out-fish long casts most of the summer.' },
      fall: { depth: [2, 6], where: 'Deeper flats near weed die-back', tip: 'Heavy autumn feeding — big baits, big beds of particles.' },
      winter: { depth: [4, 8], where: 'Deepest holes (nearly dormant)', tip: 'Very slow; single bright hookbaits over minimal feed on mild spells.' },
    },
  },
  {
    id: 'burbot',
    lv: 'Vēdzele',
    en: 'Burbot',
    ru: 'Налим',
    badge: 'VĒ',
    color: '#6d6a75',
    lures: 'Dead bait or worm bunches on the bottom after dark; rattling spoons under ice',
    spawnTemp: 'spawns at 0–4 °C, under the ice',
    seasons: {
      spring: { depth: [6, 15], where: 'Retreats to the coolest deep water', tip: 'Post-spawn fish sit deep and feed little — a night-time bonus catch at best.' },
      summer: { depth: [8, 15], where: 'Deepest, coldest basins', tip: 'Mostly inactive in warm water — target the deepest holes at night if at all.' },
      fall: { depth: [3, 8], where: 'Rock and sand edges, feeding after dark', tip: 'The bite switches on as water drops below ~10 °C — bottom rigs after sunset.' },
      winter: { depth: [1, 6], where: 'Shallower hard bottom — spawns under the ice', tip: 'The classic mid-winter night fishery: rattle a heavy spoon on the bottom.' },
    },
  },
];
